disable ejs linting for now

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -54,9 +54,9 @@ jobs:
         if: ${{ (success() || failure()) }}
         run: npm run lint:eslint:html
 
-      - name: Run ESLint Check (EJS)
-        if: ${{ (success() || failure()) }}
-        run: npm run lint:eslint:ejs
+#      - name: Run ESLint Check (EJS)
+#        if: ${{ (success() || failure()) }}
+#        run: npm run lint:eslint:ejs
 
       - name: Run ESLint Check (Markdown)
         if: ${{ (success() || failure()) }}
